In [1]:
import numpy as np
from PIL import Image
from matplotlib import pyplot as plt
import image_stitch
import scipy
from scipy import interpolate

In [37]:
import importlib
importlib.reload(image_stitch)

<module 'image_stitch' from 'c:\\Users\\mehmet.akin\\Dropbox\\BOUN 5-1\\CMPE537\\Ass2\\image_stitch.py'>

In [3]:
%matplotlib qt

In [4]:
path = "north_campus/left-1.jpg"
left1 = Image.open(path)
path = "north_campus/left-2.jpg"
left2 = Image.open(path)

In [5]:
#coords1, coords2 = image_stitch.select_pairs(left2, left1, 6)

Please select pairs one by one.


In [9]:
coords1 = np.array([[1018.50277818,  421.4985378 ],
       [ 896.37966077,  389.91497295],
       [1208.00416728,   36.17904664],
       [ 700.56155871,  156.19659307],
       [1182.7373154 ,  427.81525077],
       [ 847.951528  ,   42.49575961]])
coords1 = coords1[:, [1,0]]
coords1

array([[ 421.4985378 , 1018.50277818],
       [ 389.91497295,  896.37966077],
       [  36.17904664, 1208.00416728],
       [ 156.19659307,  700.56155871],
       [ 427.81525077, 1182.7373154 ],
       [  42.49575961,  847.951528  ]])

In [8]:
coords2 =np.array([[340.50891943, 426.42557391],
       [249.96936687, 399.05315105],
       [534.2214505 ,  70.58407662],
       [ 24.67327095, 137.9623483 ],
       [487.89888873, 424.32000292],
       [193.11895014,  34.78936979]])
coords2 = coords2[:, [1,0]]
coords2

array([[426.42557391, 340.50891943],
       [399.05315105, 249.96936687],
       [ 70.58407662, 534.2214505 ],
       [137.9623483 ,  24.67327095],
       [424.32000292, 487.89888873],
       [ 34.78936979, 193.11895014]])

In [10]:
A = image_stitch.get_matrix_A(coords1, coords2)

In [38]:
H = image_stitch.computeH(coords1, coords2, False)
H

array([[-8.75285051e-04,  5.28797257e-05,  5.33154611e-03],
       [ 4.46437994e-02, -2.51755217e-01,  4.01311496e-01],
       [-8.79509662e-01,  2.89604144e-03,  7.05814797e-04]])

In [41]:
image_stitch.get_borders(np.array(left2), H)

(0, -321, 0, 32)